[package]
name = "challenge_checker"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
derivative = "2.2.0"
termion = "*"
clap = { version = "4.3.19", features = ["derive", "cargo"] }
tinytemplate = "1.2.1"